### ISSUE TITLE
Encourage users to import specific modules

### ISSUE THREAD

**Issue by kof** [styled-components/polished#178]
I realize that `import {lighten} from 'polished'` looks smaller, but its  bad idea to promote this style, because of the growing bundle, much better would be to show `import lighten from 'polished/lighten'` in the examples.

**Comment by bhough** [comment]
@kof @mxstbr I don't believe that this syntax will actually work with the way `polished` is built currently. This would require use to build each module as a separate package inside of the main package for that import style to work (unless there's another way I'm not aware of).

The current suggested method works for bundlers that have tree-shaking, but it's debatable how widespread it's use is, so I'm not opposed to this change. However, we should be explicit about what we are asking for in this issue, as it is quite a bit more work than just updating the example.

**Comment by silverlight513** [comment]
@bhough, Would you mind giving an example of how you got this to work? 

I'm using webpack 2 as my bundler and I'm getting an error when I try this method. After looking at my bundle using webpack-bundle-analyzer I'm pretty sure that tree shaking isn't removing the packages I'm not using. Polished is standing at 8.58KB (gzipped) when I'm only using rem

```
Error: Cannot find module 'polished/rem'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/jackrimell/widget/node_modules/module-alias/index.js:33:29)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jackrimell/widget/client/components/SearchForm.js:3:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/jackrimell/widget/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jackrimell/widget/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
```

**Comment by bhough** [comment]
@SilentCicero my comment probably will cause some confusion...

What currently works is `import rem from 'polished/lib/helpers/rem'`. I'll update my original comment to reflect that we still need to update the build if we want the shorthand `polished/rem` to work.

Is that your production bundle your are analyzing? Should see comments like this `/* unused harmony export triangle */ in your dev bundle to know that tree-shaking is working.

**Comment by silverlight513** [comment]
I was looking at my production build. I'll have a look at switching to that import from libs. Thanks :)

**Comment by bhough** [comment]
@silverlight513 I'll try and take a look again today to ensure nothing has changed. 

One thing you might want to also check is that you don't have module transformations turned on in Babel. This will prevent tree-shaking from working: Your .bablerc should have the modules flag set to false similar to below:

```json
options: {  
  presets: [ 
    [ 'es2015', { modules: false } ] 
  ]         
}```

**Comment by silverlight513** [comment]
Ah damn, I'm missing that in my babel. Completely forgot I needed to add that, thanks.

I just switched to using the import you gave and it works brilliantly.

Also to note for anyone else who may come across this issue, if you're importing a helper like rem, use `import rem from 'polished/lib/helpers/rem'` but if you're importing a mixing such as clearFix use `import clearFix from 'polished/lib/mixins/clearFix'`

**Comment by mxstbr** [comment]
We can add this to the Babel plugin so it does that automatically? /cc @thejameskyle

**Comment by luftywiranda13** [comment]
yeah, I tried to do this to import `normalize` mixins, I got **-3.7KB* reduction

**Comment by silverlight513** [comment]
@mxstbr, is there an issue logged in the babel plugin repo to keep track of progress?

**Comment by bhough** [comment]
This will be addressed by #205

**Comment by eric-burel** [comment]
Hello from the future, #205 seems closed without merge, what is the state of this issue? I am setting up Babel Transform Imports to do this automatically.
