### ISSUE TITLE
Unable to play in browser console on Polished's site

### ISSUE THREAD

**Issue by Jonalogy** [styled-components/polished#595]
## Question
Haven't been able to play with Polished via browser's console on [https://polished.js.org/](https://polished.js.org/) even though the site mentions "Open the console and play around with it!"

![Screenshot 2021-11-24 at 12 47 17](https://user-images.githubusercontent.com/20838102/143176597-342f69bd-1973-40ae-ad0a-1c38b9e1932d.png)

## Relevant Information
Using chrome version 96.0.4664.55

**Comment by corymharper** [comment]
Its not in your screenshot, but the following error message appears when you load the page:

```
Uncaught TypeError: _wrapNativeSuper__default.default is not a function
    at polished.js:317:55
    at polished.js:4:78
    at polished.js:5:3
```

**Comment by corymharper** [comment]
Seems like its related to [this line](https://github.com/styled-components/polished/blob/main/docs/assets/polished.js#L317) which was changed in [this commit](https://github.com/styled-components/polished/commit/a6c86998d5902a47f5ff231af9620dff9686bf9f#diff-102e758120672e55f341e8834cec02955c62ee97456468723787d57c0541f06eR363).

**Comment by corymharper** [comment]
And as a last bit of information, this is what the object called out by the error looks like when the exception is encountered:

```
_wrapNativeSuper__default:
default: 
undefined
[[Prototype]]: 
Object
```
